---
- hosts: all
  become: yes
  become_user: isucon
  gather_facts: no
  tags:
    - dev
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
- hosts: all
  become: yes
  gather_facts: no
  tags:
    - prod
  tasks:
    - unarchive:
        copy=no
        src=https://isucon6qimage.example.com/isucon6q/local.tar.gz
        dest=/home/isucon/
        creates=/home/isucon/.local
        owner=isucon
        group=isucon